### ISSUE TITLE
Incompatibility with datadog: assumes gateway IP serves k8s API

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#1099]
To avoid the headache of configuring an IP on the host, we use a link-local IP for the default gateway, which is *not* assigned to the host side of the veth.

User **donch** on slack reports:

> by default, datadog-agent try to connect to the default GW of the container to get data from k8s api and it don’t work with 169.254.1.1 as IP

**Comment by fasaxc** [comment]
Their workaround is to run datadog with docker rather than k8s.

**Comment by caseydavenport** [comment]
Sounds like datadog is doing the wrong thing to connect to the API, and should be using the API access config that Kubernetes injects into each pod.

However, this is still relevant: #1024

**Comment by matthewdupre** [comment]
This isn't a Calico problem.  Really, it's a datadog issue, but a fix to #1024 may offer a workaround.

**Comment by chicagobuss** [comment]
I could use some guidance here - I think this is relevant to my problem but not 100% sure.  We run k8s on AWS with canal, and the datadog daemon set integration expects hostPort to be sufficient to create a dogstatsd listener on <nodeIp>:8125 for all co-located containers.

The problem is, we don't think they took into account people using an overlay network - so our nodeIp isn't listening to 8125 - the dd-agent POD is.

I see a few ways to work around this issue, but the cleanest way to fix it would be to allow all co-located pods to reference each other by a "short pod name" (you should always have a 'dd-agent' pod next to you).

Barring that, I'll need to run dogstatsd as a proper service and expose the name to all pods, which breaks the whole point of co-located monitoring agents IMO.

Any help or guidance would be appreciated, thanks.
