### ISSUE TITLE
Calico without mesos-DNS / kuberentes like cluster IP in Calico.

### ISSUE THREAD

**Issue by dp-farm** [projectcalico/calico-containers#1100]
Is there a way to do service isolation using calico in mesos without using mesos-DNS (DNS based LB will probably not yield good load-balancing distribution of backend containers)? 

e.g. iptables based kube-proxy in kubernetes maintains source IP of client pod. And thus calico can do service isolation based on 4-tuple in the packet before forwarding packet to destination pod.

But if we use a user space load balancing solution to do LB in mesos, then user-space LB will change the source IP to either docker host IP or Calico assigned IP (if LB is integrated with Calico). and thus doing service isolation will be difficult as source IP of client container has changed. 

One solution to this problem is to have an concept similar to cluster IP but implemented at Calico layer itself. To explain it further say a service 'app-1' is created, Calico assigns a cluster IP 'X' from same calico profile as is assigned to backend containers of 'app-1'. This IP 'X' is then given to each load-balancing container (LB container is present in all the docker host machines). An DNS solution meanwhile can create an A-record (to map 'app-1' name to IP 'X').

And thus request can be trapped by calico even before forwarding the packet to LB (IP 'X' which is also part of same profile as 'app-1' backend containers). LB will then forward the packet to backend container using source IP 'X' itself. 

I feel this will lead to better performance.

**Comment by djosborne** [comment]
@dp-farm I believe the new minuteman load balancer does what you are suggesting. 

To reiterate, the problem with Marathon-lb, as you said, is that containers must forward requests to the LB-in-the-middle, which will rewrite the packet in userspace before forwarding on to the final destination agent/container. What's worse, this LB is usually running on a different host, so most requests will jump across 3 hosts to go from container to container.

Minuteman solves this by running on each agent, and Dest-NAT'ing directly in kernelspace (using IP-tables nat'ing).

At this time, Minuteman can only rewrite a dest-IP to be an agent-IP, as it assumes containers will be running in host or bridge-networking. Basically, it never assumes that a container-IP is routable, which is true in cases like Calico. In order to make Minuteman compatible with networking plugins which assign cluster-addressable IPs (such as Calico), Minuteman will need to believe that container-ips are routable, and NAT to them instead of the host-ip.

If you're interested in Minuteman, and would like to see it support custom networking plugins such as Calico, please do raise your interest with the DC/OS maintainers to show your support.

**Comment by dp-farm** [comment]
Thanks @djosborne . Yes seems like minuteman will work in such use-cases.   

Though still I want to explore whether in Calico we can implement ClusterIP behaviour? i.e. assign same host-local IP 'X' from some calico profile in each node to LB-in-the-middle. And then Calico can do policy enforcement even before forwarding packets to LB-in-the-middle.    

Is that possible by any way to assign same IP (say 'X') to multiple workloads (in different host) and route only to container with IP 'X' running in same host?

**Comment by djosborne** [comment]
> Is that possible by any way to assign same IP (say 'X') to multiple workloads

Assigning the same IP to multiple workloads is currently unsupported. Calico's IP-per-container model assumes that each container is uniquely routable by its IP.

> assign same host-local IP 'X' from some calico profile in each node to LB-in-the-middle

@dp-farm I'm confused by this, can you elaborate some more?

**Comment by dp-farm** [comment]
IP 'X' is similar to kubernetes cluster IP.  So when a container (running on host 'H1') tries to connect to 'X', Calico routes it to a container which owns IP 'X' in this host (H1). 

Only difference is that instead of using Iptables to forward packets to Cluster IP ('X'), Calico itself forward the packets. That way policy enforcement can be done before LB itself. And this mode will work for user-space LB as well.

**Comment by djosborne** [comment]
Ah ok. So I believe minuteman covers this with [Virtual IPs](https://dcos.io/docs/1.7/usage/service-discovery/load-balancing/). Our goal is to integrate Calico with Minuteman so that you can use Minuteman VIPs and its distributed, smart load balancing, while still using Calico policy for security. In that scenario, each container in a particular service would have both its own Calico IP and a shared Minuteman VIP. Traffic sent to the VIP will be NAT'd to the Calico addresses. Still some work to be done there today, but we've done the initial testing to ensure that this is feasible.

Though Calico doesn't implement anything like this at the present time, it could reasonably fit in the existing data model. Would be a pretty neat feature.

**Comment by caseydavenport** [comment]
@dp-farm I'd like to get a better understanding of your requirements. 

> Only difference is that instead of using Iptables to forward packets to Cluster IP ('X'), Calico itself forward the packets.

When using the kube-proxy in iptables mode, Calico is indeed doing the forwarding of traffic.  The kube-proxy `iptables` rules are simply decoding the service IP to a real container IP address.  Calico can still enforce network policy on top of this just fine.

With solutions like iptables-kube-proxy / minuteman, there is no "man in the middle" - the load-balancing occurs as part of the network fabric itself and the source IP should be maintained.

**Comment by dp-farm** [comment]
@caseydavenport That's right. What I am suggesting only makes sense if there is a user space proxy in between which can't maintain source IP of client container.

**Comment by djosborne** [comment]
@dp-farm  This completely slipped my mind -  Marathon-LB is for N/S traffic. If you're doing E/W traffic (i.e. container to container), you should not hit the Marathon-LB entry at all.

Instead, both Mesos-DNS and Navstar can provide a DNS record for your scaled task, which, when resolved, will point to one of the Calico IPs of that task. Container A can then route directly to Container B, without having to jump to multiple nodes. Those DNS solutions are smart enough to balance to a different Container B address each time you resolve it.

**Comment by caseydavenport** [comment]
I think the resolution here is to use a distributed load balancer like the kube-proxy, which doesn't obscure the source address of traffic.

The problem with enforcing policy _before_ a man-in-the-middle load balancer is that you don't actually know which ultimate destination the traffic will be load-balanced to because that decision is up to the load balancer, not the network fabric.

Will re-visit the discussion here if / when we look into a more integrated solution with man-in-the-middle load-balancers, but closing for now.
