### ISSUE TITLE
RFC: simplify bird, bird6, confd stack by using gobgp

### ISSUE THREAD

**Issue by ishidawataru** [projectcalico/calico-containers#1102]
Currently, calico-node is running bird, bird6 and confd for BGP advertisement/configuration.
We can simplify this stack by using [GoBGP](https://github.com/osrg/gobgp).
GoBGP is a BGP implementation in golang and it can be used as a native golang library.
Combined with etcd client library, we can develop a minimal and efficient daemon for calico-node. 

This daemon reads/watches information stored in etcd, dynamically configures BGP, advertises allocated prefixes, inject received prefixes into kernel.

Current rough implementation
https://github.com/ishidawataru/calico-containers/tree/gobgp
https://github.com/ishidawataru/calico-bgp-daemon

Initial global/neighbor/prefix configuration at startup and dynamic prefix advertisement
are implemented.

If calico community thinks this is a good idea, I can continue working on this.

**Comment by lxpollitt** [comment]
@ishidawataru: This is very interesting work that I think is well worth continuing.  I was discussing with @djosborne and he's going to have a look at the rough implementation to see if any advice or suggestions or other help, plus he is a good person to help with general shepherding.  

I think one thing it would be good for us to do is create a to do list of what we think would need to be done to take this from the rough implementation to something we could ship to users.  Perhaps with some intermediate milestones like having a public demo or similar.

**Comment by ishidawataru** [comment]
@lxpollitt Thanks for the positive feedback. I'll wait for @djosborne's review.

I agree with you on having a todo list. Having a public demo also sounds good.

As for a todo list, can I edit [here](https://github.com/projectcalico/calico-containers/wiki) to create one? I'll list what feature is now lacking compared with BIRD+confd implementation.

**Comment by tomdee** [comment]
You could always use the github task list feature (https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments) either in this issue or in a followup PR?

**Comment by djosborne** [comment]
@ishidawataru Woo! I'm a huge fan of this move, and wanted to share my thoughts on it -

- This work greatly simplifies the backend architecture of calico-node. Much less components in play here, which is great
- Because of the first point, this also makes running uncontainerized Calico (directly on a host) much easier. I wrote the [fairly complicated guide on running dockerless Calico](https://github.com/projectcalico/calico-containers/blob/master/docs/DockerlessCalicoManual.md) which quickly gathered dust as it wasn't easy to have folks strapping multiple applications together. Through the work you've done here, those instructions could be replaced with just "download the calico binary and run it". Beautiful.
- You've done this work at an interesting time, as we are working on a [go implementation of libcalico and calicoctl](https://github.com/tigera/libcalico-go) and [calico-cni](https://github.com/projectcalico/calico-cni) as well. So though there's a lot of work in progress regarding golang right now, this fits in just fine.

My only uncertainty surrounding the future of this work is how Go's BGP library stacks up against BIRD. BIRD BGP is a pretty mature and accepted open source BGP stack. We chose it as it supports all the features we know we need, and the features we might need one day as well. Additionally, we've forked bird to add ipip support. I think the future of this work hinges on whether or not go-bgp can prove resilient and meet our needs as well.

So all that being said, I think the best way to allow this concept to mature is to structure it so that it's an opt-in feature in the master code path. Ideally we'd add the ability for a user to launch it using something like `calicoctl node --experimental-go` which would switch to this new backend instead of the traditional. That way we can allow it to mature at its own pace while still including the work in master. However, after digging into our startup processes, determining where that code split should happen isn't obvious to me right now. It may turn out to be complicated enough that we'd want to do a complete removal as you've implemented. In that case, this should go on its own branch / repository.

I'm going to take some more time to think through where this should live. Once that's sorted, we can open a PR and take a closer look at the implementation. Excited for the future of this work!

**Comment by ishidawataru** [comment]
@djosborne I understand your concern. As a GoBGP developer, if you have any question about GoBGP, I'm happy to answer that.
About the stability, we are already running GoBGP in a production network and have no problem so far.
About the feature, could you tell me what kind of BGP feature you need ?

As for IPIP support in forked BIRD, it seems you've only modified the code related to kernel injection and not touched BGP protocol itself. Am I right?
If so, since GoBGP itself doesn't support kernel injection, we have to implement it in the new daemon including IPIP support ( see 
https://github.com/ishidawataru/calico-bgp-daemon/blob/master/main.go#L235-L263 )

> Ideally we'd add the ability for a user to launch it using something like calicoctl node --experimental-go which would switch to this new backend instead of the traditional. 

How about simply using `--image` option of `calicoctl` ? 
We can push golang calico node image to dockerhub, and choose the image when we want to try golang implementation.

**Comment by djosborne** [comment]
@ishidawataru My concerns about resiliency weren't meant to question the stability of GoBGP, more that I'm hesitant to wipe out bird completely while we still have legacy customers who aren't expecting such a massive change. Instead, let's aim to merge this alongside the existing backend options in master.

I spoke with a few team members about the IPIP changes we've made to BIRD, but let's not worry about that implementation detail until we cross that bridge.

So let's focus on the infrastructure layout so we can get a base version merged to master soon. I've contimplated building a unique `calico/node-gobgp` image from your code so that, as you've suggested, we can run `calicoctl node --node-image=calico/node-gobgp` to run it. But I don't like the idea of maintaining two separate node images. Instead, can you refactor your branch to introduce the new service files and binaries alongside the existing ones, then add logic to choose which services to load in [rc.local](https://github.com/projectcalico/calico-containers/blob/master/calico_node/filesystem/etc/rc.local) based on some `$CALICO_GOBGP` environment variable set at startup?

**Comment by ishidawataru** [comment]
@djosborne done. please take a look.
https://github.com/ishidawataru/calico-containers/tree/dev

What do you think about moving [calico-bgp-daemon](https://github.com/ishidawataru/calico-bgp-daemon) repo under projectcalico?

**Comment by djosborne** [comment]
@ishidawataru Looking good.

I think calico-bgp-daemon belongs here in calico-containers for now. It's a small enough piece that I don't want to have to maintain its own release schedule quite yet. Its long term home might be its own repo, or maybe as a library in Felix.

Let's try the following: 
- put its source in `calico_node/calico-bgp-daemon/`
- add a makefile step: `make calico_node/bin/calico-bgp-daemon`. Could just `go build`, but ideally it'd use the `go` docker image to do a dockerized build.
- add that step as a dependency for `make node_image`.
- add a step in `node_image/Dockerfile` that adds the binary in.

Thoughts?

**Comment by ishidawataru** [comment]
@djosborne done. 
PTAL https://github.com/ishidawataru/calico-containers/tree/dev

**Comment by djosborne** [comment]
@ishidawataru Build images & containers are useful when there's a lot of dependencies, but I managed to modify the makefile step to instasll deps and build in one shot using the official golang image.

```
 calico_node/bin/bgp-calico-daemon:                                                                                                                                                                    
   -mkdir -p calico_node/bin/                                                     
   docker run \                                                                   
   -v `pwd`/calico_node/calico-bgp-daemon:/go/src/github.com/projectcalico/calico-bgp-daemon \
   -v `pwd`/calico_node/bin:/calico_node/bin \                                    
   golang:1.7 sh -c \                                                             
   'cd /go/src/github.com/projectcalico/calico-bgp-daemon/ && go get -v . && go build -o /calico_node/bin/calico-bgp-daemon .'
```

Can you update your Makefile to be the same? Then let's open this PR up and take a closer look at the code.

**Comment by ishidawataru** [comment]
@djosborne Sure. done.
https://github.com/ishidawataru/calico-containers/tree/dev

**Comment by djosborne** [comment]
@ishidawataru Looking good. Go ahead and open the PR for this.

**Comment by ishidawataru** [comment]
@djosborne Thanks for your review. Just opened a PR
