### ISSUE TITLE
calicoctl should set the ready flag for Felix

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico-containers#1282]
If the creation of a node resource through calicoctl set the Ready flag for felix, it would allow calicoctl to be used for Host protection deployments without requiring the use of etcdctl at all.

**Comment by caseydavenport** [comment]
Should it do this automatically? Or should there be a "calicoctl set ready" type command?

What does Felix do when that flag goes from true / false? Is this something that would be reasonable to expose as a "enable / disable Calico" global flag?

**Comment by matthewdupre** [comment]
@fasaxc WDYT?

**Comment by fasaxc** [comment]
@caseydavenport Felix stops when the Ready flag is set to false.  I.e. it leaves everything in the dataplane just as it is and stops processing updates until the flag is set back to true.  the intended purpose it to cover awkward upgrade scenarios where we want to pause all the felixes while we tinker with the datamodel.

How about having calicoctl check if the Ready flag exists; then, if not, automatically create it and set to true.  If it exists and it's set to false then leave as-is.  I'm keen not to add a new command that you have to run at start-of-day to initialise calico.  I'm a bit wary of exposing an explicit command since the behaviour might not be intuitive.

**Comment by robbrockbank** [comment]
Will only set the flag if it is not already set then.
