### ISSUE TITLE
No IPAM documentation

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-containers#784]
I can't find any documentation that describes Calico's IPAM behavior and how it interacts with pools.  This would be useful info for Calico users to have.

**Comment by robbrockbank** [comment]
@caseydavenport Casey - are you after beefing up our API docs in libcalico (i.e. someone writing to use libcalico), or adding some docs in calico-containers to indicate how our IPAM module assigned IPs from pools etc.  The latter is somewhat dependent on orchestrator though because it might be possible to specify which pool you choose from based on the environment.

**Comment by caseydavenport** [comment]
@robbrockbank - My original intent here was to document how our IPAM module assigns blocks and pools.  I believe I raised this after answering a number of different questions about how Calico assigns IP addresses on Slack.

Maybe this is something that needs to be documented per-orchestrator.

**Comment by caseydavenport** [comment]
Assigning to Turk since he's going to be looking into our docs in the near future.

@djosborne I think the requirement here is a doc that explains the philosophy behind Calico's IPAM behavior, why one would use it, and what it does.

**Comment by djosborne** [comment]
This issue was moved to projectcalico/calico#63
