### ISSUE TITLE
Ability to remove a calico BGP peer when using full-mesh

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-containers#830]
When using full-mesh BGP, the only way to remove a BGP peer from your cluster is like so:
```
calicoctl node stop
calicoctl node remove
```

By default, these commands should be run on the host which you are trying to remove.  However, you can remove another nodes configuration by setting the HOSTNAME variable when removing:

```
HOSTNAME=some-other-host calicoctl node remove
```

This works OK, but it requires that you know the hostname of the node that you're trying to remove (which isn't always the case, especially if the host no longer exists).

We want something like:
```
calicoctl node remove <ip address>
```

and/or a way to detect and clean up BGP peers that no longer exist.

**Comment by TrimBiggs** [comment]
It doesn't look like the `HOSTNAME=` option is documented either.

**Comment by TrimBiggs** [comment]
The `HOSTNAME=` piece is pretty hacky I think.  We should allow the user to specify and IP address or a hostname to remove.

I think we should use something similar to what @caseydavenport proposed:
```
calicoctl node remove [--host-ip=<HOST_IP> | --hostname=<HOSTNAME>]
```

**Comment by tomdee** [comment]
Just discussed with @caseydavenport and @TrimBiggs and we've decided on the following spec:

It would be good to have a `calicoctl node show` command. This should be available on Windows and Mac binaries too (along with `node remove`). 

```
Add calicoctl node show. It shows a table of

+----------+---------+---------+
| Hostname | Bird IPv4 | Bird IPv6 | AS Num | peer v4 | peer v6|
+----------+---------+---------+
+----------+---------+---------+

/calico/bgp/v1/
  `--<hostname>  # one for each Docker host in the cluster
            |--ip_addr_v4 # the IP address BIRD listens on
            |--ip_addr_v6 # the IP address BIRD6 listens on
            |--as_num     # the AS number for this host
            |--peer_v4    # Host specific IPv4 BGP peers
            |  `--<BGP peer IPv4 address>  # JSON BGP peer configuration (see below)
            `--peer_v6  # Host specific IPv6 BGP peers
               `--<BGP peer IPv6 address>  # JSON BGP peer configuration (see below)
```


And then enhance `calicoctl node remove`
- Add --force
- Add --hostname (the same as doing "sudo HOSTNAME=blah calicoctl node remove" but it's more explicit)
- No need to add --host-ip since it can be found with the `node show` command above.

**Comment by TrimBiggs** [comment]
Hey @tomdee, I'm not so sure the `--force` option is necessary.

Currently, the command will try to remove the local host and fail if:
 - The container is running (requires user to run `node stop` first)
 - The container has endpoints associated with it (pass in `--remove-endpoints` when running the command)

The changes to `node remove` allow you to pass in the hostname of the node you'd like to remove, but the command still fails if there are endpoints associated unless the user passes in `--remove-endpoints`.  It's not clear to me what usefulness the `--force` option provides here; just require the used to pass in `--force` to actually run the command, throwing a warning message if it's not passed in?  I don't think it's necessary.

**Comment by tomdee** [comment]
It's the container stop bit that I'm concerned about. What if I want to run this from a host that has the container running, but that isn't the host I'm trying to remove?

**Comment by TrimBiggs** [comment]
Spoke with Tom.  The `--force` was planned to bypass checking if the `calico/node` or `calico'node=libnetwork` containers were running on the host machine so that removing a different host would not be blocked by having either of these containers running on the host that ran the command.

Instead, I've added a check to see if the host value passed in is equal to the local hostname before running this container check.
