### ISSUE TITLE
Calico network containers unreachable from one another

### ISSUE THREAD

**Issue by BediarSofiane** [projectcalico/calico-containers#852]
Hello,
I followed the same tutorial of how to use calico with Docker containers: https://github.com/projectcalico/calico-containers/blob/master/docs/calico-with-docker/docker-network-plugin/README.md
 I have created a calico network, added 2 containers to it. but thay cannot reach each other.

Envirement:

Docker version:
root@sofiane-VirtualBox-Client1:~# docker version
Client:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   79edcc5
 Built:        Sat Feb 13 00:16:28 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   79edcc5
 Built:        Sat Feb 13 00:16:28 2016
 OS/Arch:      linux/amd64
 Experimental: true

Ubuntu kernel:
root@sofiane-VirtualBox-Client1:~# uname -a
Linux sofiane-VirtualBox-Client1 4.2.0-30-generic #36-Ubuntu SMP Fri Feb 26 00:58:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I'm using ETCD to manage the K-V store (it seems working very well).

When i create the network and the two containers (one in each ubuntu VM  host), every thing is good. but when I try to ping a container from the other one i have the ping error : "Destination host unreachable". However, withe the same conviguration, if I create an Overlay network every thing works very well and i can ping between its containers.

I believe the problem is probably whithin the host machins, but I can't figure it out.

Thank you guys

**Comment by TrimBiggs** [comment]
Hi @BediarSofiane 

Thanks for the issue, sorry to hear you're seeing this. I've got a few questions/requests to help figure this out.

If you can create an overlay network that functions, I assume you are able to ping from host to host?

With your setup at the point where it should be running, can you post output for these commands on each host:
`route -n`
`calicoctl bgp peer show`

Also, can you post the IP's of each container?  This should help diagnose the issue.

**Comment by TrimBiggs** [comment]
Hi @BediarSofiane,

Just wanted to check in and see if you have made any progress or seen any more issues like this.  Let me know if you're still having problems, and I can help solve them with you.

**Comment by BediarSofiane** [comment]
Hi @TrimBiggs ,
Thank you for your answer. In fact, i didn't really resolved the problem or know what caused it. But by restarting my etcd cluster I could reach the containers from one another. It must be some bug of the etcd cluster concerning the keys of calico. after all now it is working fine. 
However, i'm studying calico driver and the difference between it and Overlay driver, and i want some sort of documentation concerning the architecture of calico (how it really implements BGP and does routing between containers, what is the role of the tow containers calico-node and calico-libnetwork that we should start in each docker host and so on). 
I assume that those stuffs are treated in the offcial documentation of calico. so i'm going to read it and try to understand all this. If you have a good book on it a would appreciate it.

Thank you bro

**Comment by TrimBiggs** [comment]
Hi @BediarSofiane 

I'm glad you were able to get your setup working.

We don't have a book, but here are a few doc pages on our Github that I think will be useful to you:
 - [Calico Components](https://github.com/projectcalico/calico-containers/blob/master/docs/Components.md): The pieces that make up the `calico/node` container.
 - [Docker Container Lifecycle doc](https://github.com/projectcalico/calico-containers/blob/master/docs/DockerContainerLifecycle.md): a lower-level look at what happens when running Calico in a Docker cluster, from the creation of the `calico/node` to networking containers in Calico.
 - [BGP doc](https://github.com/projectcalico/calico-containers/blob/master/docs/bgp.md): explains how to configure BGP in Calico, with a bit of information on what happens when configuring.

I'm going to close the issue since you're not seeing the problem anymore, but please feel free to keep in touch here or in our Slack channels, which you can find in our main [README](https://github.com/projectcalico/calico-containers/).  Thanks for bringing up this issue :)

**Comment by padgyx** [comment]
Hi, @TrimBiggs: I have similar issue and here is the output of your request:
./calicoctl bgp peer show
No global IPv4 BGP Peers defined.

No global IPv6 BGP Peers defined.

Should I configure the global BGP Peers to make it work?

**Comment by TrimBiggs** [comment]
Hi @padgyx,

What exactly are you seeing? How is your cluster configured? How many nodes are running with calico?

Thanks

**Comment by padgyx** [comment]
Hi, TrimBiggs:

Thanks for your reply. Our company is currently evaluating Calico vs Weave. Please help get this working so that we can see the performance advantage of Calico over Weave. I provided more details in this separate ticket: https://github.com/projectcalico/calico-containers/issues/950

I have two separate AWS ec2 instances. I tried both docker-network-plugin and without. Neither of them work on the AWS ec2 instances. Please let me know what other data you need from my environment. 

In addition, I tested on Vagrant following the same instruction which works fine. 

Please help!

Thanks!

**Comment by TrimBiggs** [comment]
@padgyx Let's continue to chat on the other issue, we'll leave this one closed.
