### ISSUE TITLE
Cannot communicate with the gateway

### ISSUE THREAD

**Issue by frostynova** [projectcalico/calico-containers#898]
Calico node libnetwork plugin and docker is the latest release version

I met a strange thing:

Our pool is 172.20.0.0/16, when launching the 1st container with auto ip 172.20.0.0, everything is OK.
But the 2nd container with ip 172.20.0.1 (using different network) cannot ping to the gateway. Tcpdump on the gateway show it has received the ICMP packets.

But if we stop this container and start it again, it will be given a new ip 172.20.0.2 and everythink is OK.

I have compared the route table, the profile rule and iptables rules, 1st and 2nd containers has no different.

**Comment by frostynova** [comment]
add the diags: https://transfer.sh/NcJWP/diags-290316-045056.tar.gz

**Comment by frostynova** [comment]
add environment details:

calico node 0.18.0
libnetwork 0.8.0
docker 1.10.3
CentOS 7

**Comment by frostynova** [comment]
Calico node 0.17.0  works well

**Comment by TrimBiggs** [comment]
Hi @frostynova,

I'm going to take a look at your diags now.  That is strange behavior indeed.

Are you running your cluster in the cloud or in a local deployment?  Are the containers running on a single host or two separate hosts?

**Comment by frostynova** [comment]
@TrimBiggs all containers are in a single vagrant box

**Comment by TrimBiggs** [comment]
I couldn't find anything glaring in the logs.  I'm trying to repro now with the same setup.

As a general point, I believe there were a fair amount of IP Address Manager changes in the latest release, hopefully this hasn't caused problems.

**Comment by TrimBiggs** [comment]
I've just run through a vagrant install with CentOS using the versions you mentioned were failing.

My process was:
 - start the node with `calico/node:v0.18.0` and `calico/node-libnetwork:v0.8.0`
 - remove default 192.168.0.0/16 pool
 - add new 10.10.0.0/16 pool
 - create docker network with calico driver and calico ipam driver
 - create two docker containers (networked using calico)
 - ping between containers (success)

Is this different from your repro process (if so can you describe how)?
Are you consistently hitting this with `calico/node:v0.18.0`?

**Comment by frostynova** [comment]
I also cannot use origin docker cli to reproduce this issue.

Our environment use docker-py and 3rd-party go client to operate docker network and contains.

But I think I found the direct cause, 2nd container got an invalid mac address:

```
17: cali0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether de:9e:a7:ed:9d:7c brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.1/32 scope global cali0
       valid_lft forever preferred_lft forever
    inet6 fe80::dc9e:a7ff:feed:9d7c/64 scope link
       valid_lft forever preferred_lft forever
```

it should be ee:ee:ee:ee:ee:ee

I will go on digging this

**Comment by frostynova** [comment]
I got it

Because the bad docker api example, i thought i needed to connect the container to its network before starting it. The correct method is just creating the container with NetworkingConfig then start it directly.

@TrimBiggs Sorry to disturb your work

**Comment by frostynova** [comment]
@TrimBiggs I am confused, after i using the correct api to deploy container, this problem appeared again.

the docker network inspect show correct info:

```
[root@node1 ~]# docker network inspect deploy
[
    {
        "Name": "deploy",
        "Id": "afbbb2d801e2d99bd37d9d4f13c4035b4e8ded9dd2e2e7bce485a735d5d541cc",
        "Scope": "global",
        "Driver": "calico",
        "IPAM": {
            "Driver": "calico",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.20.0.0/16"
                }
            ]
        },
        "Containers": {
            "11f776ecba50bd5aa970ce91bd7db15d4230b141abdf4b4b72c0b3e63154917c": {
                "Name": "deploy.web.web.v0-i1-d0",
                "EndpointID": "068d118b27e40b922ca4905a5a250f75ea85e25cd1b58fece293cdd8e2ac781d",
                "MacAddress": "ee:ee:ee:ee:ee:ee",
                "IPv4Address": "172.20.0.1/32",
                "IPv6Address": ""
            }
        },
        "Options": {}
    }
]
```

but the docker exec ip addr show the container had a wrong MAC address:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
17: cali0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether c2:e1:37:5b:29:28 brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.1/32 scope global cali0
       valid_lft forever preferred_lft forever
    inet6 fe80::c0e1:37ff:fe5b:2928/64 scope link
       valid_lft forever preferred_lft forever
```

Docker daemon and calico has no error log

**Comment by TrimBiggs** [comment]
Hi @frostynova,

I'm going to look into the `calico/libnetwork-plugin` code to see where we're setting the MAC address, I'll get back shortly.

**Comment by TrimBiggs** [comment]
The libnetwork plugin only ever uses the ee:ee... MAC address for the containers.

I'm wondering if this is a bug with docker-py not accepting the MAC address that is passed to it, or if there is some other MAC address manipulation in your docker-py calls that trumps the fixed ee:ee- mac.

**Comment by frostynova** [comment]
Yep, i also took a look at the plugin code, here is my opinion:

1. `docker network inspect` show ee:ee... MAC address, that means it has been set by the plugin correctly
1.  this is the 2nd container deployed by our api call, the 1st is always ok. And i also let the docker daemon print the json it received, the difference is only network name. 
1. but inside the container, the MAC is wrong, this may because https://github.com/projectcalico/libnetwork-plugin/blob/master/libnetwork/driver_plugin.py#L423 this line not executed correctly, but i have already seen the log print by https://github.com/projectcalico/libnetwork-plugin/blob/master/libnetwork/driver_plugin.py#L447

So i wonder if there is some bugs on our vagrant system (such as iproute or even kernel). Our box is an old CentOS 7.0, i use a new CentOS 7.2 box to replace it. With the new box, i have tested twice, the problem has gone, but not sure if this is only a coincidence

Next week i will try to build a debug version libnetwork-plugin, and do more tests.

**Comment by TrimBiggs** [comment]
Hi @frostynova,

Just checking in.  I hope you've had some success with this.  Please let me know if you've had any more success/issues, and if you're still finding that it works with some version of calico/node or node-libnetwork but not others.

Thanks again for all of the info.

**Comment by robbrockbank** [comment]
Hi @frostynova,

This sounds rather odd.  From what you've described, we are going through the code branch to set the MAC on the container interface, but that it appears to be set to something else.

I'm at a bit of a loss as to what might be going on here - but perhaps there is a bug in the OS that is preventing this from working.

A couple of other questions:

-  Is this repeatable behavior, or was it a one-off?
-  What happens if you create a 3rd container - does that get networked ok, is it only the second container, is it random?

**Comment by frostynova** [comment]
@robbrockbank for your questions:

* Most of the time this problem occurs (but not all the time)
* The 3rd container is ok

Today i modified the libnetwork pluigin to let it print the `ip addr` output when join the network. The log shows it created the `tmp` interface with correct MAC Address. But i noticed a strange log in `dmesg`

```
[Tue Apr  5 11:16:56 2016] IPv6: ADDRCONF(NETDEV_UP): tmpd6cafb183d5: link is not ready
[Tue Apr  5 11:16:56 2016] IPv6: ADDRCONF(NETDEV_CHANGE): tmpd6cafb183d5: link becomes ready
[Tue Apr  5 11:29:06 2016] IPv6: ADDRCONF(NETDEV_UP): cali13e96739fa0: link is not ready
[Tue Apr  5 11:29:06 2016] IPv6: ADDRCONF(NETDEV_CHANGE): cali13e96739fa0: link becomes ready
[Tue Apr  5 11:42:14 2016] IPv6: ADDRCONF(NETDEV_UP): tmpfa63d43f99d: link is not ready
[Tue Apr  5 11:42:14 2016] IPv6: ADDRCONF(NETDEV_CHANGE): tmpfa63d43f99d: link becomes ready
```

this output show the 1st 2nd and 3rd containers' interface created by libnetwork, and the 2nd's interface name not began with `tmp`, is `cali`

But with CentOS 7.2, all interfaces in dmesg begin with `cali`

**Comment by TrimBiggs** [comment]
Hi @frostynova,

Just checking in.  Have you been continuing to see this issue?

**Comment by frostynova** [comment]
@TrimBiggs Until now, Calico with CentOS 7.2 works very well. So this issue can be closed.

**Comment by TrimBiggs** [comment]
That's great! We'll keep note of this issue and possibly write about it being a known issue with Centos 7.0 if we can't figure out the underlying problem.

Thanks again for the consistent feedback :smiley:

**Comment by nik786** [comment]
I've just run through a vagrant install with CentOS using the versions you mentioned were failing.





@TrimBiggs 
Do you think following process will work with calico 3.0 too???

start the node with calico/node:v0.18.0 and calico/node-libnetwork:v0.8.0
remove default 192.168.0.0/16 pool
add new 10.10.0.0/16 pool
create docker network with calico driver and calico ipam driver
create two docker containers (networked using calico)
ping between containers using container names and IPs (success)
Is this different from your repro process (if so can you describe how)?
Are you consistently hitting this with calico/node:v0.18.0?

**Comment by nik786** [comment]
if i do use iptables -F on worker node then pods start to ping each other across different nodes
but after 2 secs all calico rules come back and stop pinging
is anyone have idea how to solve this???

**Comment by caseydavenport** [comment]
@nik786 this issue is quite old - could you please open a new one for what you're seeing now?

**Comment by nik786** [comment]
@caseydavenport 



./calico -v
v3.1.1

./calicoctl version
Client Version:    v3.1.1

./calico-ipam -v
v3.1.1

cni version is 0.30.0

/opt/bin/etcdctl -version
etcdctl version: 3.0.10

/opt/bin/etcd -version
etcd Version: 3.0.10



core-1:172.17.8.101

./calicoctl node run --ip 172.17.8.101

./calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 172.17.8.102 | node-to-node mesh | up    | 08:26:38 | Established |
| 172.17.8.103 | node-to-node mesh | up    | 08:26:47 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.

ip r
10.1.11.0/24 dev docker0 proto kernel scope link src 10.1.11.1 linkdown 
172.17.0.0/16 dev eth1 proto kernel scope link src 172.17.8.101 
192.168.174.0/26 via 172.17.8.102 dev eth1 proto bird 
192.168.210.128/26 via 172.17.8.103 dev eth1 proto bird 

route -n
10.1.11.0       0.0.0.0         255.255.255.0   U     0      0        0 docker0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eth1
192.168.174.0   172.17.8.102    255.255.255.192 UG    0      0        0 eth1
192.168.210.128 172.17.8.103    255.255.255.192 UG    0      0        0 eth1


etcdctl ls /calico/v1/ipam/v4/pool/

/calico/v1/ipam/v4/pool/192.168.0.0-16

core-01 calico # kubectl get  pods --all-namespaces -o wide | grep calico
kube-system            calico-kube-controllers-6ddfbf7775-j8qkz   1/1       Running   1          15h       172.17.8.103      172.17.8.103


core2:172.17.8.102

./calicoctl node run --ip 172.17.8.102

./calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 172.17.8.101 | node-to-node mesh | up    | 08:26:37 | Established |
| 172.17.8.103 | node-to-node mesh | up    | 08:26:46 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.

ip r

172.18.0.0/16 dev docker0 proto kernel scope link src 172.18.0.1 linkdown 
blackhole 192.168.174.0/26 proto bird 
192.168.210.128/26 via 172.17.8.103 dev eth1 proto bird 

route -n

172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.174.0   0.0.0.0         255.255.255.192 U     0      0        0 *
192.168.210.128 172.17.8.103    255.255.255.192 UG    0      0        0 eth1

core-02#ping 192.168.210.129

nt pinging


core-3:172.17.8.103

./calicoctl node run --ip 172.17.8.103

core-03 bin # ./calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 172.17.8.101 | node-to-node mesh | up    | 08:26:46 | Established |
| 172.17.8.102 | node-to-node mesh | up    | 08:26:46 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.



ip r
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.174.0   172.17.8.102    255.255.255.192 UG    0      0        0 eth1
192.168.210.128 0.0.0.0         255.255.255.192 U     0      0        0 *
192.168.210.132 0.0.0.0         255.255.255.255 UH    0      0        0 cali2fcb7f3501f

route -n
192.168.174.0   172.17.8.102    255.255.255.192 UG    0      0        0 eth1
192.168.210.128 0.0.0.0         255.255.255.192 U     0      0        0 *
192.168.210.132 0.0.0.0         255.255.255.255 UH    0      0        0 cali2fcb7f3501f


core-03# ping 192.168.174.15
nt pinging

kubelet service

/opt/bin/kubelet --kubeconfig=/opt/bin/kubeconfig    --address=0.0.0.0  --hostname_override=172.17.8.103  --cluster-dns=10.254.0.15  --cluster-domain=cluster.local --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --v=0


proxy service

/opt/bin/kube-proxy   --proxy-mode=iptables --master=https://172.17.8.101:6443  --v=2

core-03 system # cat /etc/cni/net.d/10-calico.conf 
{
    "name": "calico-k8s-network",
    "cniVersion": "0.3.0",
    "type": "calico",
    "etcd_endpoints": "http://127.0.0.1:2379",
    "log_level": "debug",
    "ipam": {
        "type": "calico-ipam"
    },
    "policy": {
        "type": "k8s"
    },
    "kubernetes": {
        "kubeconfig": "/opt/bin/kubeconfig"
    }

}



can any one tell me how to set up pod to pod pinging across calico nodes with out flashing iptables ???


this is the present ip range in following services


apiserver.service

--service-cluster-ip-range=10.254.0.0/24

controller.service

--cluster-cidr=10.254.0.0/16

kubelet

--cluster-dns=10.254.0.15
