### ISSUE TITLE
Cannot comunicate containers in diferent networks by name

### ISSUE THREAD

**Issue by amon-ra** [projectcalico/calico-containers#912]
I have setup 1 node calico cluster but name resolving is not working.
I can ping with ip address but name resolving is not working

```
alpine:/var/log# calicoctl profile net1 rule show 
Inbound rules:
   1 allow from tag net1
   2 allow from tag net2
Outbound rules:
   1 allow

alpine:/var/log# calicoctl profile net2 rule show 
Inbound rules:
   1 allow from tag net2
   2 allow from tag net1
Outbound rules:
   1 allow

docker run --net net2 --name p2 -dit busybox
docker run --net net1 --name p1 -dit busybox

alpine:/var/log# docker exec -it p2 /bin/sh
/ # cat /etc/hosts
192.168.0.3	dfbee5c89e08
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
/ # ping p1
ping: bad address 'p1'
/ # ping p1.net1
ping: bad address 'p1.net1'

alpine:/var/log# docker info
Containers: 5
Images: 37
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.20-0-grsec
Operating System: Alpine Linux v3.3
CPUs: 1
Total Memory: 3.074 GiB
Name: alpine
ID: VMAT:MZ4E:52DF:SX7F:EJ4R:LUTH:HT43:PFPW:4DVM:KO2T:XJUX:2OTI
WARNING: No swap limit support
Cluster store: etcd://127.0.0.1:2379

```

Any ideas?

**Comment by lxpollitt** [comment]
I don't think Calico gets involved in name resolution.  @TrimBiggs @robbrockbank @tomdee may better understand and be able to comment.

**Comment by TrimBiggs** [comment]
@amon-ra, Alex is right, Calico does not get involved with name resolution.  Docker does, however.  I'll look into how Docker DNS works.  There may be some parameters to pass to Docker so that all containers get host entries, regardless of the network they are attached to, or some way to turn off host entry writes so you could use your own DNS (this is speculation, though).

**Comment by frostynova** [comment]
According to some docker issues, with user defined network, libnetwork will give the container an embedded dns `127.0.0.11`.

This is a dns cache, if you use docker overlay, it will resolve container name, and bypass all the others dns request to the dns address which specified during creating the container.

And there is still no way to disable this feature: https://github.com/docker/docker/issues/19474

**Comment by bboreham** [comment]
@amon-ra is using Docker 1.9.1; Docker DNS was added in 1.10, so it's irrelevant.

More fundamentally, the two containers are connected to different Docker networks, so Docker thinks you don't expect them to see each other.

If you set up an upstream DNS, Docker should punt to that.

**Comment by TrimBiggs** [comment]
Thank you for chipping in @frostynova and @bboreham.

By the sounds of it, we would not expect these two containers to have name resolution between each other since Calico does not get involved with name resolution and Docker does not provide hostname entries in a container to containers in different networks.
