### ISSUE TITLE
There is no work when i use "-e CALICO_IP=auto -e CALICO_PROFILE=test"  to run a container

### ISSUE THREAD

**Issue by workhardcc** [projectcalico/calico-containers#932]
hi guys,
i have three etcd node(physical matchine), run calico container in each of them. My docker listen port is :
> cat /etc/sysconfig/docker 
OPTIONS="-b=bond0 -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"
DOCKER_CERT_PATH=/etc/docker

Then i hijack docker port  to calico as below:`export DOCKER_HOST=localhost:2375`
At last run a container as `docker run --name test3 -e CALICO_IP=auto -e CALICO_PROFILE=test -tid base_centos6`. Container runs well but i didn't found any new nic in this container . If i use calicoctl add a ip to this container manual is successful.
ip pool as blow:

> +-------------+-------------------+
|  IPv4 CIDR  |      Options      |
+-------------+-------------------+
| 10.1.0.0/16 | ipip,nat-outgoing |
+-------------+-------------------+

thanks a lot!

**Comment by TrimBiggs** [comment]
Hi @workhardcc,

Looks like you caught some outdated docs from our repo! We no longer use the `CALICO_IP` or `CALICO_PROFILE` environment variables, but it looks like we still have some leftover references to them in our FAQ and Troubleshooting guides.  I also don't think you need to specify `DOCKER_HOST`, Calico should just connect to `unix://var/run/docker.sock`.

Could you tell us a bit more about your setup and goal? Are you wanting to configure a base Calico-networked cluster to try it out?

You could try following one of our guides on installing Calico, such as [Calico as a Docker Network Plugin](https://github.com/projectcalico/calico-containers/tree/master/docs/calico-with-docker/docker-network-plugin)(this is probably what you're looking for) or [Calico without Docker Networking](https://github.com/projectcalico/calico-containers/tree/master/docs/calico-with-docker/without-docker-networking).

Let me know if those guides help or if you have any other questions!

**Comment by workhardcc** [comment]
Thanks for your relay!
My test environment consist of three physical machine, one is mesos master(marathon,zookeeper service on this node)， the other two of them are mesos slave and  deployed etcd、docker service and run a calico container. The goal is: make a new container by marathon, calico can assign a independent ip from ip pool. So i want calico can auto deploy a ip to a new container by command line first.That's it. Thanks again.

**Comment by TrimBiggs** [comment]
Thanks for the info! That's important to know.

The idea behind Calico with Mesos is to provide Calico integration within the actual tasks that are run by Marathon.  It makes most sense for the IP assignment to be within the actual task definition so that you do not have to run Calico each time the task runs.

We have hooks into Marathon that allow you to specify that you'd like to assign an IP to the task.  The best way to do this (using the Docker Containerizer) would be to follow our [Docker Containerizer Usage Guide](https://github.com/projectcalico/calico-containers/blob/master/docs/mesos/UsageGuideDockerContainerizer.md) within our Mesos docs.

The basic required steps for your case are to:
**Run the Calico node and node-libnetwork containers:**
```sudo calicoctl node --libnetwork```
**Create a Docker network that uses Calico as the driver:**
```docker network create --driver calico my_net```
**Launch the Marathon task with the the Docker network as a parameter**
 (see the Docker Containerizer Usage Guide).

Those steps should get you started with a Calico networked task.  If you'd like, you could also follow the [Stars demo](https://github.com/projectcalico/calico-containers/tree/master/docs/mesos/stars-demo) to see how Calico policy is used in a visualized demo (you'll need Vagrant and Virtualbox to run this).

Let me know how this goes!

**Comment by TrimBiggs** [comment]
Hey @workhardcc,

Any luck with this?  I'm going to close down this issue since I've made the docs fix for the initial problem you hit.  Please feel free to reopen it if you are still running into any roadblocks.

Thanks!

**Comment by workhardcc** [comment]
Ok! Thanks for your help!
